Fix warning on build if local.yaml doesn't exist
fourkitchens/scrummy-react-dom pull request #29
Opened 2017-01-14 05:08 UTC by ccjjmartin

## Purpose:
- Fix warning on build if local.yaml doesn't exist

## Reproduce bug:
- Get a fresh copy of scrummy
- Run `yarn`
- Run `npm run build`
- Notice this warning:
```
WARNING in ./config/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./local.yaml in /Users/developer/repos/contrib/scrummy-react-dom/config
 @ ./config/index.js 9:16-39
```

## Notes:
- It appears that someone has looked into this before because it is enclosed in a try catch
- I looked into using the fs module to check if the file exists with no luck.  Apparently webkit doesn't like the fs module and this might be because this is eventually sent into someone's browser.
- After much trial and error with the fs module I decided it was easier to just commit a blank local.yaml file.  It is still in the .gitignore file so subsequent changes should not be committed.

## Testing:
- Follow the reproduce bug steps but notice the error is gone.

2017-01-15 05:31 UTC, infiniteluke requested changes
This is great work! A couple of wording nits in the readme. Thanks!

2017-01-15 05:31 UTC, infiniteluke commented on docs/backend.md
> +* The default is to connect to the Herokuapp at ws://scrummy-server.herokuapp.com.
Can we have this read: "The deployed application connects to ws://scrummy-server.herokuapp.com."

2017-01-15 05:31 UTC, infiniteluke commented on docs/backend.md
> +* Open two terminal windows and start up both dev servers with `npm run start` in the projects root directories.
"...start up both apps..."

sp "projects'"

2017-01-15 05:34 UTC, infiniteluke commented
I only have `apiUrl: ws://localhost:8001` in my `local.yml`

2017-01-15 18:29 UTC, ccjjmartin commented
@infiniteluke Thanks for the quick reviews on these.  I updated the docs for your comments except the one about sp "projects".  I haven't seen the abbreviation sp before.  I am guessing that is spelling error.  If so, I went with the plural of "projects" to refer to both projects rather than the possessive "project's" which would seem to only refer to one.  I can update this to "project's" if you prefer though.  Let me know if sp means something else.

2017-01-18 19:58 UTC, infiniteluke commented
Hey @ccjjmartin - Yes, sp was a bit cryptic, but you're right, I meant spelling error. In this case we'll still want to use `projects'` since it is possessive of their directories and there are multiple of them (server/client).

2017-01-30 18:39 UTC, infiniteluke approved these changes

2017-01-30 18:39 UTC, merged