Initial Card component
fourkitchens/scrummy-react-dom pull request #3
Opened 2016-09-15 04:05 UTC by infiniteluke

Just to make sure coverage stuff is working right, here's a simple component.

2016-09-15 04:22 UTC, infiniteluke commented
The codecov commenting will be enabled by this PR.

2016-09-16 01:08 UTC, flipactual commented on .codeclimate.yml
> +  - "**.js"
Can this be indented another level? That's how I tend to write yml, but tbh I have no idea which is "right"

2016-09-16 01:09 UTC, flipactual commented on .storybook/config.js
> +configure(loadStories, module);
Can `loadStories` be made anonymous/arrow and just passed in to `configure`?

2016-09-16 01:11 UTC, flipactual commented on src/components/Card/Card.scss
> +.card.selected {
Maybe `.card.is-selected`?

2016-09-16 01:12 UTC, flipactual commented on src/components/Card/index.js
> +  <div className={`card ${selected ? 'selected' : ''}`}>
Might be good to go ahead and pull in [`classnames`](https://github.com/JedWatson/classnames)

2016-09-16 01:13 UTC, flipactual commented on src/components/Card/stories.js
> +const value = 13;
I still prefer to caps lock my `const`s, but I'm just chiming in, not concerned.

2016-09-16 01:58 UTC, flipactual commented on src/index.html
> -<html manifest="feelings.appcache">
I'm dead

2016-09-16 02:00 UTC, flipactual commented on test/Card.js
> +import { render } from 'enzyme';
neat

2016-09-16 02:02 UTC, flipactual requested changes
Few nits to discuss for maximum funness.

2016-09-16 02:11 UTC, infiniteluke commented on src/components/Card/index.js
> +  <div className={`card ${selected ? 'selected' : ''}`}>
I wondered. Good call.

2016-09-16 02:12 UTC, infiniteluke commented on src/components/Card/Card.scss
> +.card.selected {
I agree this sounds better, but I'm trying to keep classnames/markup as backwards compatible as possible to make @tsmith512's life easy.

2016-09-16 02:13 UTC, infiniteluke commented on src/index.html
> -<html manifest="feelings.appcache">
No more feelings

2016-09-16 03:11 UTC, infiniteluke commented
@flipactual Ready for review again.

2016-09-16 03:12 UTC, flipactual commented on src/components/Card/Card.scss
> +.card.selected {
👌

2016-09-16 03:12 UTC, flipactual approved these changes

2016-09-16 03:12 UTC, merged

2016-09-16 03:14 UTC, fluxsauce commented on src/index.html
> -<html manifest="feelings.appcache">
☠️